#
# Copyright 2023 Johns Hopkins University
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# The base docker-compose file for eclipse-pass.org deployments
# DO NOT CALL THIS directly, instead look at specific environments
#
#  - eclipse-pass.demo.yml
#  - eclipse-pass.nightly.yml
services:
  pass-core:
    image: "ghcr.io/eclipse-pass/pass-core-main:${PASS_VERSION}"
    container_name: pass-core
    env_file:
      - .env
    networks:
      - back

  pass-ui:
    image: "ghcr.io/eclipse-pass/pass-ui:${PASS_VERSION}"
    container_name: pass-ui
    env_file:
      - .env
    networks:
      - back

volumes:
  db:
    driver: local

networks:
  front:
    driver: bridge
  back:
    driver: bridge
    ipam:
      config:
        # 172.23.0.0/16 is already used by avalon-docker_avalon-network on this host.
        - subnet: 172.24.0.0/16
